// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { blogPosts } from "npm:@/data/blogPosts";
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts on CognitionX (Russian-language CBT/schema-therapy blog by psychologist Dmitry Yatsko). Returns slug, title, description, date, and tags for each post. Filter by tag optionally.",
  inputSchema: {
    tag: z.string().optional().describe("Optional tag filter (case-insensitive substring match)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max number of posts to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ tag, limit }) => {
    const t = tag?.toLowerCase();
    const filtered = blogPosts.filter((p) => !t || p.tags.some((x) => x.toLowerCase().includes(t))).sort((a, b) => (b.date || "").localeCompare(a.date || "")).slice(0, limit ?? 50).map((p) => ({
      slug: p.slug,
      title: p.title,
      description: p.description,
      date: p.date,
      updatedAt: p.updatedAt,
      tags: p.tags,
      url: `https://cognitionx.cloud/blog/${p.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { posts: filtered, total: filtered.length }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { blogPosts as blogPosts2 } from "npm:@/data/blogPosts";
function stripHtml(html) {
  return html.replace(/<br\s*\/?>/gi, "\n").replace(/<\/p>/gi, "\n\n").replace(/<\/li>/gi, "\n").replace(/<li[^>]*>/gi, "- ").replace(/<[^>]+>/g, "").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\n{3,}/g, "\n\n").trim();
}
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch the full plain-text body of a CognitionX blog post by its slug. Returns title, description, tags, dates, and markdown-like body.",
  inputSchema: {
    slug: z2.string().min(1).describe("Blog post slug, e.g. 'kpt-pri-depressii'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const post = blogPosts2.find((p) => p.slug === slug);
    if (!post) {
      return {
        content: [{ type: "text", text: `No blog post with slug "${slug}".` }],
        isError: true
      };
    }
    const body = post.content.map((b) => {
      if (b.type === "heading") {
        const hashes = "#".repeat((b.level || 2) + 1);
        return `${hashes} ${stripHtml(b.text)}`;
      }
      if (b.type === "quote") return `> ${stripHtml(b.text)}`;
      if (b.type === "component") return `_[interactive component: ${b.componentId}]_`;
      return stripHtml(b.text);
    }).filter(Boolean).join("\n\n");
    const result = {
      slug: post.slug,
      title: post.title,
      description: post.description,
      date: post.date,
      updatedAt: post.updatedAt,
      tags: post.tags,
      url: `https://cognitionx.cloud/blog/${post.slug}`,
      body
    };
    return {
      content: [{ type: "text", text: `# ${post.title}

${post.description}

${body}` }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-tests.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { tests } from "npm:@/data/tests";
var list_tests_default = defineTool3({
  name: "list_psychological_tests",
  title: "List psychological tests",
  description: "List validated self-report psychological tests available on CognitionX (PHQ-9, GAD-7, BAT, PSS-10, etc.). Returns slug, code, title, cluster, and duration. Filter by cluster (e.g. 'depression', 'anxiety', 'burnout').",
  inputSchema: {
    cluster: z3.string().optional().describe(
      "Optional cluster filter: depression, anxiety, burnout, stress, self-esteem, it, cbt-tools, trauma, sleep, addiction, relationships, personality, eating."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ cluster }) => {
    const items = tests.filter((t) => !cluster || t.cluster === cluster).map((t) => ({
      slug: t.slug,
      code: t.code,
      title: t.title,
      cluster: t.cluster,
      clusterLabel: t.clusterLabel,
      durationMin: t.durationMin,
      audience: t.audience,
      url: `https://cognitionx.cloud/tools/tests/${t.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { tests: items, total: items.length }
    };
  }
});

// src/lib/mcp/tools/search-blog.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
import { blogPosts as blogPosts3 } from "npm:@/data/blogPosts";
var search_blog_default = defineTool4({
  name: "search_blog",
  title: "Search blog",
  description: "Full-text search across CognitionX blog posts (title, description, tags, body). Case-insensitive substring match. Returns matching posts with slug, title, and a short snippet.",
  inputSchema: {
    query: z4.string().min(1).describe("Search query (Russian or English)."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.toLowerCase();
    const results = blogPosts3.map((p) => {
      const body = p.content.map((b) => b.text).join(" ").replace(/<[^>]+>/g, " ");
      const haystack = `${p.title}
${p.description}
${p.tags.join(" ")}
${body}`.toLowerCase();
      const idx = haystack.indexOf(q);
      if (idx === -1) return null;
      const snippet = haystack.slice(Math.max(0, idx - 80), idx + 200).replace(/\s+/g, " ").trim();
      return {
        slug: p.slug,
        title: p.title,
        description: p.description,
        tags: p.tags,
        url: `https://cognitionx.cloud/blog/${p.slug}`,
        snippet: `\u2026${snippet}\u2026`
      };
    }).filter((x) => x !== null).slice(0, limit ?? 10);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results, total: results.length }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cognitionx-mcp",
  title: "CognitionX MCP",
  version: "0.1.0",
  instructions: "Read-only tools for CognitionX (Russian CBT and schema-therapy resource by psychologist Dmitry Yatsko). Use `list_blog_posts` and `search_blog` to discover articles, `get_blog_post` to read the full body, and `list_psychological_tests` to enumerate validated self-report tests (PHQ-9, GAD-7, BAT, etc.). All content is public.",
  tools: [list_blog_posts_default, get_blog_post_default, list_tests_default, search_blog_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
