// AUTO-GENERATED by scripts/fetch-db-posts.mjs — DO NOT EDIT.
// 0 published post(s) fetched at 2026-07-28T06:08:23.232Z
// Regenerate with: bun run scripts/fetch-db-posts.mjs
import type { BlogPost } from "./blogPosts";

export const dbBlogPosts: BlogPost[] = [];
