// AUTO-GENERATED by scripts/fetch-db-posts.mjs — DO NOT EDIT.
// 0 published post(s) fetched at 2026-08-23T05:03:36.092Z
// Regenerate with: bun run scripts/fetch-db-posts.mjs
import type { BlogPost } from "./blogPosts";

export const dbBlogPosts: BlogPost[] = [];
