// AUTO-GENERATED by scripts/fetch-db-posts.mjs — DO NOT EDIT.
// 0 published post(s) fetched at 2026-07-22T09:59:12.714Z
// Regenerate with: bun run scripts/fetch-db-posts.mjs
import type { BlogPost } from "./blogPosts";

export const dbBlogPosts: BlogPost[] = [];
